import { describe,it,expect } from 'vitest';
import { node,resetFunnelLayout } from './funnelModel';
import { buildPipelineEdges } from './pipelineModel';
import { editPipelineConnection,connectionError,connectedNextStage } from './pipelineConnections';
const fixture=()=>[node('job','Workflow',null,'job'),node('stage','Screening','job','screen'),node('trip','Trip','screen','trip'),node('stage','Interview','job','interview'),node('communication','Thanks','screen','message')];
describe('direct pipeline connections',()=>{
 it('reattaches a message and preserves port choices across reset',()=>{const original=fixture();const next=editPipelineConnection(original,{source:'trip',target:'message',sourceHandle:'out-right',targetHandle:'in-left'},{source:'screen',target:'message'});expect(next.find(n=>n.id==='message')?.parent).toBe('trip');expect(original.find(n=>n.id==='message')?.parent).toBe('screen');expect(buildPipelineEdges(next).some(e=>e.source==='screen'&&e.target==='message')).toBe(false);expect(resetFunnelLayout(next)[0].canvasConnections).toEqual(next[0].canvasConnections);});
 it('removes links without deleting nodes or recreating the default edge',()=>{const next=editPipelineConnection(fixture(),null,{source:'screen',target:'trip'});expect(next).toHaveLength(5);expect(next.find(n=>n.id==='trip')?.parent).toBe(null);expect(buildPipelineEdges(next).some(e=>e.source==='screen'&&e.target==='trip')).toBe(false);expect(next.find(n=>n.id==='screen')?.destinationId).toBe('__disconnected__');});
 it('rejects self links, reverse cycles, and ownership cycles',()=>{const nodes=fixture();expect(connectionError(nodes,{source:'trip',target:'trip'})).toBeTruthy();expect(connectionError(nodes,{source:'interview',target:'screen'})).toBeTruthy();expect(()=>editPipelineConnection(nodes,{source:'trip',target:'job'})).toThrow();});
 it('updates the next-stage destination and replaces old connector metadata',()=>{const nodes=fixture();const first=editPipelineConnection(nodes,{source:'trip',target:'interview'});const next=editPipelineConnection(first,{source:'screen',target:'interview',sourceHandle:'out-bottom',targetHandle:'in-top'},{source:'trip',target:'interview'});expect(next.find(n=>n.id==='screen')?.destinationId).toBe('interview');expect(next[0].canvasConnections).toHaveLength(1);});
});

it('follows an activity chain to the next stage and stops at a removed link',()=>{const original=fixture();const linked=editPipelineConnection(original,{source:'screen',target:'trip'});expect(connectedNextStage(linked,'screen')?.id).toBe('interview');expect(connectedNextStage(linked.map(n=>({...n,collapsed:true})),'screen')?.id).toBe('interview');const removed=editPipelineConnection(linked,null,{source:'trip',target:'interview'});expect(connectedNextStage(removed,'screen')).toBeUndefined();});

it('allows a message to point back to its owner through a side port',()=>{const linked=editPipelineConnection(fixture(),{source:'message',target:'trip',sourceHandle:'out-left',targetHandle:'in-right'});expect(linked.find(n=>n.id==='message')?.parent).toBe('trip');expect(buildPipelineEdges(linked).some(e=>e.source==='message'&&e.target==='trip')).toBe(true);expect(buildPipelineEdges(linked).some(e=>e.source==='trip'&&e.target==='message')).toBe(false);const removed=editPipelineConnection(linked,null,{source:'message',target:'trip'});expect(removed.find(n=>n.id==='message')?.parent).toBe(null);});

it('does not connect dropped nodes automatically',()=>{const nodes=[...fixture(),{...node('stage','Loose stage',null,'loose-stage'),manual:true},{...node('trip','Loose Trip',null,'loose-trip'),manual:true,placeholder:true}];expect(buildPipelineEdges(nodes).some(e=>[e.source,e.target].some(id=>id.startsWith('loose-')))).toBe(false);const connected=editPipelineConnection(nodes,{source:'loose-stage',target:'loose-trip'});expect(buildPipelineEdges(connected).filter(e=>e.source==='loose-stage')).toEqual([expect.objectContaining({target:'loose-trip'})]);});
